@echo off
rem Bullsyey build, run & report
rem using msbuild
rem solution generated by premake5

SETLOCAL
set _me=%~n0
call %~dp0_cmd\_be_setup.cmd %*

set cleanCmd=msbuild -t:clean -p:configuration=%config% %solution%
set buildCmd=msbuild -t:%trg% -p:configuration=%config% %solution%

call %subsDir%\_be_report.cmd noreport
