@echo off
rem Bullsyey build, run & report
rem using msbuild
rem solution generated by premake5

SETLOCAL
set _me=%~n0
call %~dp0_be_setup.cmd %*

set cleanCmd=gnumake -j clean
set buildCmd=gnumake -j config=%config%

call %myDir%\_be_report.cmd
