@echo off
rem Bullsyey build, run & report
rem using msbuild, docopts, covbr2html
rem solution generated by premake5

SETLOCAL

cd %~dp0
set _me=%~nx0
set myDir=%cd%
cd ..
set rootDir=%cd%
set testsDir=%cd%\tests
set srcDir=%cd%\code
set buildDir=%cd%\build
set binDir=%cd%\submodules\sombin
set reportsDir=%CD%\reports_bullseye

set tmpCmd=%myDir%\tmp.cmd
set solution=%myDir%\Tests.sln
set runSub=%myDir%\be_build_n_run.cmd

if not exist %solution% (
    echo use premake5 to generate %solution%
    exit /b 1
)

rem required tools
set docopts=%binDir%\somcpp\docopts.exe
set covbr2html=%binDir%\covbr2html\covbr2html.exe
for %%f in (%docopts% %covbr2html%) do (
    if not exist %%f (
        echo %%~nxf not found
        exit /b 1
    )
)

md %buildDir% 2>NUL

set optsTxt=%myDir%\be_options.txt

%docopts% %optsTxt% %* > %tmpCmd%
call %tmpCmd%
del %tmpCmd% 2>NUL

rem help
if %_h% (
    echo usage: %_me% [options] [targets]
    type %optsTxt%
    exit /b 0
)

rem list targets
if %_l% (
    echo targets:
    for %%f in (%testsDir%\*.cpp) do echo %%~nf
    exit /b 0
)

rem clean build and reports
if %_c% (
    del /Q /S %buildDir% >NUL 2>&1
    del /Q /S %reportsDir% >NUL 2>&1
)

rem enable HTML (uppercase H option)
set _html=%_Hu%

@REM md %reportsDir% 2>NUL

rem rebase to source dir
rem enable macros
set covcopt=--srcdir %srcDir% --macro

set start=%time%

if "%_args%"=="" (
    for %%f in (%testsDir%\*.cpp) do call %runSub% %%~nf
) else (
    for %%f in (%_args%) do call %runSub% %%f
)

%covbr2html% -co %reportsDir% %buildDir%\todo_*.txt

echo %start%
echo %time%
