@echo off
rem Bullsyey build, run & report
rem using msbuild, docopts, covbr2html
rem solution generated by premake5

SETLOCAL

cd %~dp0
set _me=%~nx0
set myDir=%cd%
cd ..
set rootDir=%cd%
set testsDir=%cd%\tests
set srcDir=%cd%\code
set buildDir=%cd%\build
set binDir=%cd%\submodules\sombin
set reportsDir=%CD%\reports

set tmpCmd=%buildDir%\tmp.cmd
set solution=%myDir%\Tests.sln
set runSub=%myDir%\be_build_n_run.cmd

if not exist %solution% (
    echo %solution% not found
    echo use premake5 to generate
    exit /b 1
)

rem required tools
set docopts=%binDir%\somcpp\docopts.exe
set covbr2html=%binDir%\covbr2html\covbr2html.exe
for %%f in (%docopts% %covbr2html%) do (
    if not exist %%f (
        echo %%~nxf not found
        exit /b 1
    )
)

md %buildDir% 2>NUL

set optsTxt=%myDir%\be_options.txt

%docopts% %optsTxt% %* > %tmpCmd%
call %tmpCmd%

if %_h% (
    echo usage: %_me% [options] [targets]
    type %optsTxt%
    exit /b 0
)
if %_l% (
    echo targets:
    for %%f in (%testsDir%\*.cpp) do echo %%~nf
    exit /b 0
)

if %_c% (
    del /Q /S %buildDir% >NUL 2>&1
    del /Q /S %reportsDir% >NUL 2>&1
)
set _html=%_Hu%

md %reportsDir% 2>NUL

set covcopt=--srcdir %srcDir% --macro

if "%_args%"=="" (
    for %%f in (%testsDir%\*.cpp) do call %runSub% %%~nf
) else (
    for %%f in (%_args%) do call %runSub% %%f
)

%covbr2html% -co %reportsDir% %buildDir%\todo_*.txt
