@echo off
rem Bullsyey build, run & report
rem using msbuild, docopts, covbr2html
rem solution generated by premake5

SETLOCAL

set _me=%~nx0
set tool=bullseye
call %~dp0setup.cmd %*
if %errorlevel% NEQ 0 exit /b 0

set runSub=%myDir%\be_build_n_run.cmd

rem rebase to source dir
rem enable macros
set covcopt=--srcdir %srcDir% --macro

if "%_args%"=="" (
    for %%f in (%testsDir%\*.cpp) do call %runSub% %%~nf
) else (
    for %%f in (%_args%) do call %runSub% %%f
)

%covbr2html% -co %reportsDir% %buildDir%\todo_*.txt

echo %start%
echo %time%
