@echo off
rem Bullsyey build, run & report
rem using msbuild, docopts, covbr2html
rem solution generated by premake5

SETLOCAL

set _me=%~nx0
set tool=bullseye
call %~dp0setup.cmd %*
if %errorlevel% NEQ 0 exit /b 0

set runSub=%myDir%\be_build_n_run.cmd
set covReport=%reportsDir%\coverage.txt
echo %DATE% %TIME% > %covReport%

rem rebase to source dir
rem enable macros
set covcopt=--srcdir %srcDir% --macro --no-banner

if "%_args%"=="" (
    for %%f in (%testsDir%\*.cpp) do call %runSub% %%~nf
) else (
    for %%f in (%_args%) do call %runSub% %%f
)

echo finish
%pyDir%\covbr2html\covbr2html.py -co %reportsDir% %buildDir%\todo_*.txt
echo report: %covReport%
echo.
echo %start%
echo %time%
