@echo off
rem CTC build, run & report
rem using ctclaunch msbuild
rem solution generated by premake5

SETLOCAL
set _me=%~n0
call %~dp0ctc_setup.cmd

call be_off.cmd
echo - clean
call msbuild /t:clean %solution% >NUL 2>&1
if exist %symFile% rm -f %symFile%
if exist %covFile% rm -f %covFile%
echo - build
call ctclaunch %ctclaunchParams% msbuild %solution% /t:%trg% %msbuildParams% > %buildReport% 2>&1
if not exist %executable% (
    echo - build failed
    cat %buildReport%
    set eCode=1
    goto end
) else (
    rm -f %buildReport%
)
echo - run
call %executable%
echo - report
call %reportCall%
:end
call be_restore.cmd
exit /b %eCode%
