@echo off
rem CTC build, run & report
rem using ctclaunch msbuild
rem solution generated by premake5

SETLOCAL
set _me=%~n0
call %~dp0_cmd\_ctc_setup.cmd %*
if %errorlevel% NEQ 0 exit /b 0

set cleanCmd=msbuild -t:clean -p:configuration=%config% %solution%
set buildCmd=ctclaunch %ctclaunchParams% msbuild -t:%trg% %msbuildParams% -p:configuration=%config% %solution%

call %subsDir%\_ctc_report.cmd
