@echo off
rem CTC build, run & report
rem using ctclaunch gnumake
rem make file generated by premake5

SETLOCAL
set _me=%~n0
call %~dp0ctc__setup.cmd

echo - clean
call gnumake -f %makefile% clean >NUL 2>&1
echo - build
call ctclaunch %ctclaunchParams% gnumake -j -f %makefile% > %buildReport% 2>&1

call %myDir%\ctc__run.cmd
